### ISSUE TITLE
请求添加 Power's Wiki

### ISSUE THREAD

**Issue by linyuxuanlin** [Jexbat/DoHard#1]
- 博客地址：https://wiki-power.com
- 方向：硬件、嵌入式
- RSS：（仅部分内容）https://wiki-power.com/blog/rss.xml

**Comment by JesseGuoX** [comment]
@linyuxuanlin  已加，博客不错，涉猎也很广👍

**Comment by linyuxuanlin** [comment]
感谢感谢！😄

**Comment by JesseGuoX** [comment]
现在写博客的很少了，都转去写公众号了，公众号太封闭了，基本无法索引，当前这个里面罗列的有些网站也不更新了，过一阵重新整理一下。

**Comment by linyuxuanlin** [comment]
其实不是的，仍有很多人在默默写博客，当然也有很全的中文博客列表，像 [rss-sub-list](https://github.com/saveweb/rss-list) 项目。我也有公众号，但不常更新文章，如你所说，公众号这些平台太封闭了，也不方便后期修改。一般来说，文章偏向于写给别人看的就去公众号，偏向于写给自己的还是会自建博客。
